# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/GripperActionController
  action_ns: gripper_cmd
  publish_rate: 100
  joint: right_finger_joint
  action_monitor_rate: 50
  state_publish_rate:  100
  stalled_velocity_threshold: 0.001
  goal_tolerance: 0.05
  stall_timeout: 0.1
